<script>
    /*
     * Copyright (c) "Neo4j"
     * Neo4j Sweden AB [http://neo4j.com]
     *
     * This file is part of Neo4j.
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     *     http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */

    export let size = 8;

    let badgeNames = [
        "001-sunset-1.png",
        "002-moai.png",
        "003-ambulance-1.png",
        "004-sunset.png",
        "005-map.png",
        "006-ambulance.png",
        "007-traffic-light-1.png",
        "008-field.png",
        "009-police-car-1.png",
        "010-traffic-light.png",
        "011-harvest.png",
        "012-formula-1.png",
        "013-ship-1.png",
        "014-church-1.png",
        "015-trolley.png",
        "016-traffic-sign.png",
        "017-japan.png",
        "018-bank-1.png",
        "019-yatch.png",
        "020-church.png",
        "021-boat-1.png",
        "022-building-5.png",
        "023-sailboat.png",
        "024-school.png",
        "025-kayak.png",
        "026-sit.png",
        "027-shop.png",
        "028-satellite.png",
        "029-hotel.png",
        "030-rocket.png",
        "031-bank.png",
        "032-arrivals.png",
        "033-hospital.png",
        "034-departures.png",
        "035-building-4.png",
        "036-airplane-1.png",
        "037-building-3.png",
        "038-gas-station.png",
        "039-bus-2.png",
        "040-torii-gate.png",
        "041-airplane.png",
        "042-building-2.png",
        "043-helicopter.png",
        "044-building-1.png",
        "045-train-11.png",
        "046-house-3.png",
        "047-train-10.png",
        "048-house-2.png",
        "049-train-9.png",
        "050-house-1.png",
        "051-train-8.png",
        "052-house.png",
        "053-train-7.png",
        "054-factory.png",
        "055-train-6.png",
        "056-crane.png",
        "057-train-5.png",
        "058-road.png",
        "059-train-4.png",
        "060-railway.png",
        "061-barrier.png",
        "062-car-2.png",
        "063-building.png",
        "064-train-3.png",
        "065-tent.png",
        "066-train-2.png",
        "067-camping.png",
        "068-train-1.png",
        "069-desert.png",
        "070-volcano.png",
        "071-train.png",
        "072-mountain-2.png",
        "073-cable-car-cabin-2.png",
        "074-mountain-1.png",
        "075-cable-car-cabin-1.png",
        "076-mountain.png",
        "077-cable-car-cabin.png",
        "078-taxi-1.png",
        "079-island.png",
        "080-car-1.png",
        "081-sun-umbrella-1.png",
        "082-sun-umbrella.png",
        "083-ufo.png",
        "084-bus-1.png",
        "085-synagogue.png",
        "086-taxi.png",
        "087-anchor.png",
        "088-cityscape-5.png",
        "089-carousel.png",
        "090-police-car.png",
        "091-ship.png",
        "092-cityscape-4.png",
        "093-flasher.png",
        "094-roller-coaster.png",
        "095-night.png",
        "096-motorcycle.png",
        "097-scooter.png",
        "098-ferris-wheel.png",
        "099-cityscape-3.png",
        "100-stadium.png",
        "101-cityscape-2.png",
        "102-bicycle.png",
        "103-kick-scooter.png",
        "104-cityscape-1.png",
        "105-castle-1.png",
        "106-tractor.png",
        "107-cityscape.png",
        "108-castle.png",
        "109-delivery-truck-1.png",
        "110-eiffel-tower.png",
        "111-fireworks-1.png",
        "112-delivery-truck.png",
        "113-fountain.png",
        "114-fireworks.png",
        "115-statue-of-liberty.png",
        "116-shooting-star.png",
        "117-bus.png",
        "118-mosque.png",
        "119-car.png",
        "120-boat.png",
        "acorn.png",
        "apple.png",
        "balloons.png",
        "bear.png",
        "bee.png",
        "beehive.png",
        "bench.png",
        "bicycle.png",
        "bird.png",
        "birdhouse.png",
        "bush.png",
        "butterfly.png",
        "caterpillar.png",
        "chick.png",
        "deer.png",
        "dragonfly.png",
        "duck.png",
        "flamingo.png",
        "flower-pot.png",
        "flowers.png",
        "forest.png",
        "fountain.png",
        "fox.png",
        "gnome.png",
        "grasshopper.png",
        "grill.png",
        "hammock.png",
        "hedgehog.png",
        "hot-air-balloon.png",
        "hummingbird.png",
        "juice.png",
        "ladybug.png",
        "log.png",
        "mountain.png",
        "mushroom.png",
        "nest.png",
        "orange.png",
        "owl.png",
        "picnic-basket.png",
        "pinwheel.png",
        "rabbit.png",
        "roller-skate.png",
        "shovel.png",
        "snail.png",
        "squirrel.png",
        "strawberry.png",
        "sun.png",
        "tree.png",
        "tulips.png",
        "watering-can.png",
    ];
    let badgeUrl = `/images/badges/${badgeNames[Math.floor(Math.random() * badgeNames.length)]}`;
    let badgeClass = `h-${size} w-${size} rounded-full border-2 border-blue-200`;
</script>

<img class={badgeClass} src={badgeUrl} alt="" />
